#include "core.h"

void    ADD  (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    ADDCS(uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    ADDS (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    ADDR (uint32_t *Rd, uint32_t Operand);
void    ANDS (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    B    (uint32_t cc);
void    BICS (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    BKPT (uint32_t imm);
void    BL   (void     *label);
void    BLX  (uint32_t *Rm);
void    BX   (uint32_t *Rm);
void    CMN  (uint32_t *Rn, uint32_t *Rm);
uint8_t CMP  (uint32_t *Rn, uint32_t Operand);
void    CPSID(uint32_t i);
void    CPSIE(uint32_t i);
void    DMB  (void);
void    DSB  (void);
void    EORS (uint32_t *Rd, uint32_t *Rn, uint32_t *Rm);
void    ISB  (void);
void    LDM  (uint32_t *Rt, uint32_t **reglist);
void    LDR  (uint32_t *Rt, void     *label);
void    LDRB (uint32_t *Rt, uint32_t *Rn, void     *label);
void    LDRH (uint32_t *Rt, uint32_t *Rn, void     *label);
void    LDRSB(uint32_t *Rt, uint32_t *Rn, void     *label);
void    LDRSH(uint32_t *Rt, uint32_t *Rn, void     *label);
void    LSLS (uint32_t *Rt, uint32_t *Rn, void     *label);
void    LSRS (uint32_t *Rt, uint32_t *Rn, void     *label);
void    MOV  (uint32_t *Rd, uint32_t *Rm);
void    MOVS (uint32_t *Rd, uint16_t  Rm);
void    MRS  (uint32_t *Rd, uint32_t *spec_reg);
void    MSR  (uint32_t *Rd, uint32_t *spec_reg);
void    MULS (uint32_t *Rd, uint32_t *Rn, uint32_t *Rm);
void    MVNS (uint32_t *Rd, uint32_t *Rm);
void    NOP  (void);
void    OR   (uint32_t *Rd, uint32_t *Rn, uint32_t *Rm);
void    POP  (uint32_t **reglist);
void    PUSH (uint32_t **reglist);
void    REV  (uint32_t *Rd, uint32_t *Rm);
void    REV16(uint32_t *Rd, uint32_t *Rm);
void    REVSH(uint32_t *Rd, uint32_t *Rm);
void    RORS (uint32_t *Rd, uint32_t *Rn, uint32_t *Rm);
void    RSUBS(uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    SEV  (void);
void    STM  (uint32_t *Rt, uint32_t **reglist);
void    STR  (uint32_t *Rt, uint32_t **reglist);
void    STRB (uint32_t *Rt, uint32_t **reglist);
void    STRH (uint32_t *Rt, uint32_t **reglist);
void    SUB  (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    SUBCS(uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    SUBS (uint32_t *Rd, uint32_t *Rn, uint32_t Operand);
void    SVC  (uint16_t imm);
void    SXTB (uint32_t *Rd, uint32_t *Rm);
void    SXTH (uint32_t *Rd, uint32_t *Rm);
void    TST  (uint32_t *Rn, uint32_t *Rm);
void    UXTB (uint32_t *Rd, uint32_t *Rm);
void    UXTH (uint32_t *Rd, uint32_t *Rm);
void    WFE  (void);
void    WFI  (void);
